version: "3.1"

services:
  server:
    build: .
    depends_on:
      pg:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: 5432
      POSTGRES_TZ: America/Detroit
      TODO_ENV: development
    develop:
      watch:
        - action: rebuild
          path: ./main.go

  pg:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DATABASE}"]

  adminer:
    image: adminer
    depends_on:
      pg:
        condition: service_healthy
    restart: always
    ports:
      - "9000:8080"

volumes:
  pgdata:
